### ISSUE TITLE
Issue running under Windows 10

### ISSUE THREAD

**Issue by alexgoldstone** [weiway/node-serialport-worker#4]
On Windows 10 I have installed electron using:

```
npm install -g electron-prebuilt
```

I then created a new project using `npm init` and installed `node-serialport-worker` using:

```
npm install serial-worker --save
```

My application simply does:

```
const electron = require('electron');
const serial = require('serial-worker');
...
...
...
...
serial.list((e,ports)=>{
    console.log(ports)
});
```

When I try to run I get:

```
App threw an error when running [Error: A dynamic link library (DLL) initialization routine failed.
\\?\Z:\Desktop\winplc\node_modules\serialport\build\Release\node-v47-win32-x64\serialport.node]
ATOM_SHELL_ASAR.js:157
        return old.apply(this, arguments);
                   ^

Error: A dynamic link library (DLL) initialization routine failed.
\\?\Z:\Desktop\winplc\node_modules\serialport\build\Release\node-v47-win32-x64\serialport.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:157:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:157:20)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (Z:\Desktop\winplc\node_modules\serialport\serialport.js:14:25)
    at Module._compile (module.js:425:26)
```

Any guidance will be appreciated.

**Comment by weiway** [comment]
This is problem with the serialport module and electron itself. Which node and electron version you are using? Usually you need to rebuild the serialport module with electron-rebuild

**Comment by alexgoldstone** [comment]
Thank you for the reply. Since `node-serialport-worker` is specifically for use with Electron I incorrectly assumed things should "just work".

I am using:
- Windows 10
- Node.js 5.9.0
- Electron 0.37.2

Are you able to a dive what build tools are required to be installed and what steps to follow?

[This comment](https://gist.github.com/jedthehumanoid/a7f8278e0a37d259adca#gistcomment-1720266) suggests using `electron-rebuild` with the `PreGypFix` option but that doesn't mean much to me yet.

**Comment by weiway** [comment]
This package is mainly to solve the high cpu usage of serialport module inside electron, but you just bring a interesting question. I think I might remove serialport from dependencies and let this module work side by side with serialport 

As far as I know, `electron-rebuild` is the way to solve this problem. However, there might be problems with path/name of the rebuilt native module. You can use `PreGypFix` or you can fix it yourself by renaming it.

I'll will close this issue for now.

**Comment by weiway** [comment]
@alexgoldstone This might be helpful

For future reference:
https://github.com/voodootikigod/node-serialport/issues/538
