### ISSUE TITLE
Disconnecting and then reconnecting causes events to be emitted twice.

### ISSUE THREAD

**Issue by jayalfredprufrock** [weiway/node-serialport-worker#6]
I've noticed that after disconnecting and reconnecting, subsequent write requests are triggered twice. If I disconnect and reconnect another time, events are triggered 3 times. Looks like events or the process aren't being removed properly.

**Comment by jayalfredprufrock** [comment]
I should add that I'm creating a new SerialPort port instance each connection. I properly clean up all of the events I register in the "close" event and then subsequently delete the instance object before making a new connection. This didn't cause issues with node-serialport but perhaps there is a better way? I'm doing it like this because I need to be able to change the SerialPort options in between connection attempts, but perhaps modifying the SerialPort object's options directly is preferred?

**Comment by weiway** [comment]
In general, I definitely think change serialport settings would be a way to look into, since always creating new SerialPort instance might lead to possible memory leak.
But since you mentioned you could do this in serialport, I'll looking to see if there's any event listener not removed correctly

**Comment by jayalfredprufrock** [comment]
Thanks @welway, this package has successfully solved some memory issues I was having with node-serialport so I'm determined to get serial-worker fully integrated into my project.

As a workaround to the above problem, I was able to get things working by calling `reporter.removeAllListeners()` in my close event on the serialport object. 

Of course, I'm concerned about memory leaks too, but I'm still not sure how I can change the actual serial port path in between connections without creating a new SerialPort instance. I believe node-serialport suffers from the same problem, but if I'm missing something do let me know. Thanks!

**Comment by weiway** [comment]
Yes, I've figured this solution. calling `reporter.removeAllListeners()` is the correct way. 
However, you need to clear listeners after every `serial.write()` call.

I have fixed this problem and you can now install the latest version from npm.

Let me know if you have other problems.
